In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# Any results you write to the current directory are saved as output.

In [ ]:
df = pd.read_csv("emails.csv")
df.head(20)

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0             0.00               0.64           0.64           0.0   
1             0.21               0.28           0.50           0.0   
2             0.06               0.00           0.71           0.0   
3             0.00               0.00           0.00           0.0   
4             0.00               0.00           0.00           0.0   
5             0.00               0.00           0.00           0.0   
6             0.00               0.00           0.00           0.0   
7             0.00               0.00           0.00           0.0   
8             0.15               0.00           0.46           0.0   
9             0.06               0.12           0.77           0.0   
10            0.00               0.00           0.00           0.0   
11            0.00               0.00           0.25           0.0   
12            0.00               0.69           0.34           0.0   
13            0.00               0.00           0.00           0.0   
14            0.00               0.00           1.42           0.0   
15            0.00               0.42           0.42           0.0   
16            0.00               0.00           0.00           0.0   
17            0.00               0.00           0.00           0.0   
18            0.00               0.00           0.55           0.0   
19            0.00               0.63           0.00           0.0   

    word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
0            0.32            0.00              0.00                0.00   
1            0.14            0.28              0.21                0.07   
2            1.23            0.19              0.19                0.12   
3            0.63            0.00              0.31                0.63   
4            0.63            0.00              0.31                0.63   
5            1.85            0.00              0.00                1.85   
6            1.92            0.00              0.00                0.00   
7            1.88            0.00              0.00                1.88   
8            0.61            0.00              0.30                0.00   
9            0.19            0.32              0.38                0.00   
10           0.00            0.00              0.96                0.00   
11           0.38            0.25              0.25                0.00   
12           0.34            0.00              0.00                0.00   
13           0.90            0.00              0.90                0.00   
14           0.71            0.35              0.00                0.35   
15           1.27            0.00              0.42                0.00   
16           0.94            0.00              0.00                0.00   
17           0.00            0.00              0.00                0.00   
18           1.11            0.00              0.18                0.00   
19           1.59            0.31              0.00                0.00   

    word_freq_order  word_freq_mail  ...  char_freq_%3B  char_freq_%28  \
0              0.00            0.00  ...          0.000          0.000   
1              0.00            0.94  ...          0.000          0.132   
2              0.64            0.25  ...          0.010          0.143   
3              0.31            0.63  ...          0.000          0.137   
4              0.31            0.63  ...          0.000          0.135   
5              0.00            0.00  ...          0.000          0.223   
6              0.00            0.64  ...          0.000          0.054   
7              0.00            0.00  ...          0.000          0.206   
8              0.92            0.76  ...          0.000          0.271   
9              0.06            0.00  ...          0.040          0.030   
10             0.00            1.92  ...          0.000          0.000   
11             0.00            0.00  ...          0.022          0.04

In [ ]:
df.isnull().sum()

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                0
word_freq_font                0
word_freq_000                 0
word_freq_money               0
word_freq_hp                  0
word_freq_hpl                 0
word_freq_george              0
word_freq_650                 0
word_freq_lab                 0
word_freq_labs                0
word_freq_telnet              0
word_fre

In [ ]:
df.describe()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
count     4601.000000        4601.000000    4601.000000   4601.000000   
mean         0.104553           0.213015       0.280656      0.065425   
std          0.305358           1.290575       0.504143      1.395151   
min          0.000000           0.000000       0.000000      0.000000   
25%          0.000000           0.000000       0.000000      0.000000   
50%          0.000000           0.000000       0.000000      0.000000   
75%          0.000000           0.000000       0.420000      0.000000   
max          4.540000          14.280000       5.100000     42.810000   

       word_freq_our  word_freq_over  word_freq_remove  word_freq_internet  \
count    4601.000000     4601.000000       4601.000000         4601.000000   
mean        0.312223        0.095901          0.114208            0.105295   
std         0.672513        0.273824          0.391441            0.401071   
min         0.000000        0.000000          0.000000            0.000000   
25%         0.000000        0.000000          0.000000            0.000000   
50%         0.000000        0.000000          0.000000            0.000000   
75%         0.380000        0.000000          0.000000            0.000000   
max        10.000000        5.880000          7.270000           11.110000   

       word_freq_order  word_freq_mail  ...  char_freq_%3B  char_freq_%28  \
count      4601.000000     4601.000000  ...    4601.000000    4601.000000   
mean          0.090067        0.239413  ...       0.038575       0.139030   
std           0.278616        0.644755  ...       0.243471       0.270355   
min           0.000000        0.000000  ...       0.000000       0.000000   
25%           0.000000        0.000000  ...       0.000000       0.000000   
50%           0.000000        0.000000  ...       0.000000       0.065000   
75%           0.000000        0.160000  ...       0.000000       0.188000   
max           5.260000       18.180000  ...       4.385000       9.752000   

       char_freq_%5B  char_freq_%21  char_freq_%24  char_freq_%23  \
count    4601.000000    4601.000000    4601.000000    4601.000000   
mean        0.016976       0.269071       0.075811       0.044238   
std         0.109394       0.815672       0.245882       0.429342   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.315000       0.052000       0.000000   
max         4.081000      32.478000       6.003000      19.829000   

       capital_run_length_average  capital_run_length_longest  \
count                 4601.000000                 4601.000000   
mean                     5.191515                   52.172789   
std                     31.729449                  194.891310   
min                      1.000000                    1.000000   
25%                      1.588000                    6.000000   
50%                      2.276000                   15.000000   
75%                      3.706000                   43.000000   
max                   1102.500000                 9989.000000   

       capital_run_length_total        class  
count               4601.000000  4601.000000  
mean                 283.289285     0.394045  
std                  606.347851     0.488698  
min                    1.000000     0.000000  
25%                   35.000000     0.000000  
50%                   95.000000     0.000000  
75%                  266.000000     1.000000  
max                15841.000000     1.000000  

[8 rows x 58 columns]

In [ ]:
df.corr()

word_freq_make  word_freq_address  word_freq_all  \
word_freq_make                    1.000000          -0.016759       0.065627   
word_freq_address                -0.016759           1.000000      -0.033526   
word_freq_all                     0.065627          -0.033526       1.000000   
word_freq_3d                      0.013273          -0.006923      -0.020246   
word_freq_our                     0.023119          -0.023760       0.077734   
word_freq_over                    0.059674          -0.024840       0.087564   
word_freq_remove                  0.007669           0.003918       0.036677   
word_freq_internet               -0.003950          -0.016280       0.012003   
word_freq_order                   0.106263          -0.003826       0.093786   
word_freq_mail                    0.041198           0.032962       0.032075   
word_freq_receive                 0.188459          -0.006864       0.048254   
word_freq_will                    0.105801          -0.040398       0.083210   
word_freq_people                  0.066438          -0.018858       0.047593   
word_freq_report                  0.036780          -0.009206       0.008552   
word_freq_addresses               0.028439           0.005330       0.122113   
word_freq_free                    0.059386          -0.009117       0.063906   
word_freq_business                0.081928          -0.018370       0.036262   
word_freq_email                   0.053324           0.033500       0.121923   
word_freq_you                     0.128243          -0.055476       0.139329   
word_freq_credit                  0.021295          -0.015806       0.031111   
word_freq_your                    0.197049          -0.018191       0.156651   
word_freq_font                   -0.024349          -0.008850      -0.035681   
word_freq_000                     0.134072          -0.020502       0.123671   
word_freq_money                   0.188155           0.001984       0.041145   
word_freq_hp                     -0.072504          -0.043483      -0.087924   
word_freq_hpl                    -0.061686          -0.038211      -0.062459   
word_freq_george                 -0.066424          -0.030307      -0.108886   
word_freq_650                    -0.048680          -0.029221      -0.050648   
word_freq_lab                    -0.041251          -0.021940      -0.057726   
word_freq_labs                   -0.052799          -0.027508      -0.032547   
word_freq_telnet                 -0.039066          -0.018097      -0.038927   
word_freq_857                    -0.032058          -0.003326      -0.061870   
word_freq_data                   -0.041014          -0.024903      -0.054759   
word_freq_415                    -0.027690          -0.004303      -0.061706   
word_freq_85                     -0.044954          -0.024058      -0.048335   
word_freq_technology             -0.054673          -0.028198      -0.046504   
word_freq_1999                   -0.057312          -0.024013      -0.067015   
word_freq_parts                  -0.007960          -0.008922       0.032407   
word_freq_pm                     -0.011134          -0.019124      -0.014809   
word_freq_direct                 -0.036095          -0.014821      -0.047066   
word_freq_cs                     -0.009703          -0.015420      -0.030956   
word_freq_meeting                -0.026070          -0.025177      -0.005811   
word_freq_original               -0.024292          -0.002370      -0.044325   
word_freq_project                -0.022116          -0.019739      -0.053464   
word_freq_re                     -0.037105          -0.016418      -0.050664   
word_freq_edu                    -0.034056          -0.023858      -0.056655   
word_freq_table                  -0.000953          -0.009818       0.029339   
word_freq_conference             -0.017755          -0.015747      -0.026344   
char_freq_%3B                    -0.026505          -0.007282      -0.033213   
char_freq_%28               

# Data Preprocessing

In [ ]:
X = df.iloc[:,1:3001]
X

word_freq_address  word_freq_all  word_freq_3d  word_freq_our  \
0                  0.64           0.64           0.0           0.32   
1                  0.28           0.50           0.0           0.14   
2                  0.00           0.71           0.0           1.23   
3                  0.00           0.00           0.0           0.63   
4                  0.00           0.00           0.0           0.63   
...                 ...            ...           ...            ...   
4596               0.00           0.62           0.0           0.00   
4597               0.00           0.00           0.0           0.00   
4598               0.00           0.30           0.0           0.00   
4599               0.00           0.00           0.0           0.32   
4600               0.00           0.65           0.0           0.00   

      word_freq_over  word_freq_remove  word_freq_internet  word_freq_order  \
0               0.00              0.00                0.00             0.00   
1               0.28              0.21                0.07             0.00   
2               0.19              0.19                0.12             0.64   
3               0.00              0.31                0.63             0.31   
4               0.00              0.31                0.63             0.31   
...              ...               ...                 ...              ...   
4596            0.31              0.00                0.00             0.00   
4597            0.00              0.00                0.00             0.00   
4598            0.00              0.00                0.00             0.00   
4599            0.00              0.00                0.00             0.00   
4600            0.00              0.00                0.00             0.00   

      word_freq_mail  word_freq_receive  ...  char_freq_%3B  char_freq_%28  \
0               0.00               0.00  ...          0.000          0.000   
1               0.94               0.21  ...          0.000          0.132   
2               0.25               0.38  ...          0.010          0.143   
3               0.63               0.31  ...          0.000          0.137   
4               0.63               0.31  ...          0.000          0.135   
...              ...                ...  ...            ...            ...   
4596            0.00               0.00  ...          0.000          0.232   
4597            0.00               0.00  ...          0.000          0.000   
4598            0.00               0.00  ...          0.102          0.718   
4599            0.00               0.00  ...          0.000          0.057   
4600            0.00               0.00  ...          0.000          0.000   

      char_freq_%5B  char_freq_%21  char_freq_%24  char_freq_%23  \
0               0.0          0.778          0.000          0.000   
1               0.0          0.372          0.180          0.048   
2               0.0          0.276          0.184          0.010   
3               0.0          0.137          0.000          0.000   
4               0.0          0.135          0.000          0.000   
...             ...            ...            ...            ...   
4596            0.0          0.000          0.000          0.000   
4597            0.0          0.353          0.000          0.000   
4598            0.0          0.000          0.000          0.000   
4599            0.0          0.000          0.000          0.000   
4600            0.0          0.125          0.000          0.000   

      capital_run_length_average  capital_run_length_longest  \
0                          3.756                          61   
1                          5.114                         101   
2                          9.821                         485   
3                          3.537                          40   
4                          3.537                          40   
...                          ...                         ...   
45

In [ ]:
Y = df.iloc[:,-1].values
Y

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
train_x,test_x,train_y,test_y = train_test_split(X,Y,test_size = 0.25)

# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier as KNN

# Build the KNN Regressor Model
model = KNN(n_neighbors = 5, metric = 'minkowski', p = 2)
model.fit(train_x,train_y)
y_pred1 = model.predict(test_x)
conf_mat=confusion_matrix(y_pred1,test_y)
print(conf_mat)
print(classification_report(test_y, y_pred1))


[[570 119]
 [114 348]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       684
           1       0.75      0.75      0.75       467

    accuracy                           0.80      1151
   macro avg       0.79      0.79      0.79      1151
weighted avg       0.80      0.80      0.80      1151



# Naive Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB(alpha=1.9)         # alpha by default is 1. alpha must always be > 0. 
# alpha is the '1' in the formula for Laplace Smoothing (P(words))
mnb.fit(train_x,train_y)
y_pred2 = mnb.predict(test_x)
#print("Accuracy Score for Naive Bayes : ", accuracy_score(y_pred1,test_y))
conf_mat=confusion_matrix(y_pred2,test_y)
print(conf_mat)
print(classification_report(test_y, y_pred2))

[[581  68]
 [119 383]]
              precision    recall  f1-score   support

           0       0.90      0.83      0.86       700
           1       0.76      0.85      0.80       451

    accuracy                           0.84      1151
   macro avg       0.83      0.84      0.83      1151
weighted avg       0.84      0.84      0.84      1151



# Support Vector Machines

In [ ]:
from sklearn.svm import SVC
svc = SVC(C=1.0,kernel='rbf',gamma='auto')         
# C here is the regularization parameter. Here, L2 penalty is used(default). It is the inverse of the strength of regularization.
# As C increases, model overfits.
# Kernel here is the radial basis function kernel.
# gamma (only used for rbf kernel) : As gamma increases, model overfits.
svc.fit(train_x,train_y)
y_pred3 = svc.predict(test_x)
# print("Accuracy Score for SVC : ", accuracy_score(y_pred2,test_y))
conf_mat=confusion_matrix(y_pred3,test_y)
print(conf_mat)
print(classification_report(test_y, y_pred3))

[[604  71]
 [ 96 380]]
              precision    recall  f1-score   support

           0       0.89      0.86      0.88       700
           1       0.80      0.84      0.82       451

    accuracy                           0.85      1151
   macro avg       0.85      0.85      0.85      1151
weighted avg       0.86      0.85      0.86      1151



# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(train_x,train_y)
y_pred4=lr.predict(test_x)
conf_mat=confusion_matrix(y_pred4,test_y)
print(conf_mat)
print(classification_report(test_y, y_pred4))

[[679   4]
 [  5 463]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       684
           1       0.99      0.99      0.99       467

    accuracy                           0.99      1151
   macro avg       0.99      0.99      0.99      1151
weighted avg       0.99      0.99      0.99      1151



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


# Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state = 20, max_depth = 3) 
model = model.fit(train_x,train_y)
y_pred5 = model.predict(test_x)
conf_mat=confusion_matrix(y_pred5,test_y)
print(conf_mat)
print(classification_report(test_y, y_pred5))

[[684   0]
 [  0 467]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       684
           1       1.00      1.00      1.00       467

    accuracy                           1.00      1151
   macro avg       1.00      1.00      1.00      1151
weighted avg       1.00      1.00      1.00      1151

